<h1><b>Introduction to Variables</h1></b>

<br>A TensorFlow <b>variable</b> is the recommended way to represent shared, persistent state your program manipulates. This guide covers how to create, update, and manage instances of <codet>tf.Variable</code> in TensorFlow.

<br><br>Variables are created and tracked via the <code>tf.Variable</code> class. .A <code>tf.Variable</code> represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor. Higher level libraries like <code>tf.keras</code> use <code>tf.Variable</code> to store model parameters.

In [ ]:
import tensorflow as tf
import numpy as np

<h1> Create a variable</h1>
<br><br> To create a variable, provide an initial value. The <code>tf.Variable</code> will have the same <code>dtype</code> as the initialization value.

In [3]:
my_tensor = tf.constant([[1.0,2.0],[3.0,4.0]])
my_variable = tf.Variable(my_tensor)

bool_variable = tf.Variable([False,False,False,True])
complex_variable = tf.Variable([5+4j, 6_1j])

A variable looks and acts like a tensor, and, in fact, is a data structure backed by a <code> tf.Tensor</code>. Like tensors, they have a <code>dtype</code> and a shape, and can be explorted to NumPy.

In [4]:
print("Shape: ", my_variable.shape)
print("DType: ",my_variable.dtype)
print("As NumPy: ",my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


Most tensor operations work on variables but variables cannot be reshaped. 

In [5]:
print("A variable as a tensor:" , tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.math.argmax(my_variable))
#using tf.reshape on a variable just creates a new tensor, it does not reshape it
print("\"Reshaping\"", tf.reshape(my_variable, [1,4]))

A variable as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)
"Reshaping" tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)
